---
- name: Rate-limit SSH connections
  community.general.ufw:
    rule: limit
    port: "{{ ssh_port }}"
    proto: tcp

- name: Allow public HTTP and HTTPS traffic
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ firewall_http_ports }}"

- name: Deny incoming traffic by default
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Allow outgoing traffic by default
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: Enable firewall
  community.general.ufw:
    state: enabled
    logging: low
